version: "3.8"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: paper_search_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: paper_search_qdrant
    ports:
      - "6333:6333"